Xilinx/ACCL

driver/xrt/src/accl.cpp
test/host/xrt/test.cpp

Call reset_periph config function on deinit in xrt driver to reset CCLO.
~Note that the xrt driver still throws a CCLO appears configured error on subsequent runs (see #63).~ This was a problem with the test not calling the destructor.

Properly deinit cclo with xrt driver

---

driver/xrt/CMakeLists.txt
test/model/emulator/cclo_emu.cpp
test/model/simulator/cclo_sim.cpp

Applications that use ACCL fail linking because libzmq and pthreads are missing.
Also cleaned some not used includes from the simulator and emulator.

Dependency cleanup

---

test/model/bfm/cclo_bfm.cpp

In BFM::pop_data, `idx` is not explicitly initiliazed to 0 so it is indeterminate. This may cause the while loop to exit early.

Initialize counter to prevent non-deterministic behavor

---

driver/xrt/docs/getting_started/streaming.rst
driver/xrt/include/accl.hpp
driver/xrt/include/cclo.hpp
driver/xrt/src/accl.cpp
test/host/hls/test.cpp
test/host/xrt/test.cpp

Add an additional function signature for `send`, `recv`, and `stream_put` for using CCLO data streams.
This PR refers to #98.
Should collectives also support streaming?

Improve streaming in C++ API

---

test/host/xrt/test.cpp

This resolves the need to manually set the `session_id` in [communicator.cpp](https://github.com/Xilinx/ACCL/blob/da11ec6b9f50eb7e765aef3843d109ff1afc133e/driver/xrt/src/communicator.cpp#L68) and remove `open_con` in [accl.cpp](https://github.com/Xilinx/ACCL/blob/da11ec6b9f50eb7e765aef3843d109ff1afc133e/driver/xrt/src/accl.cpp#L1165), which also needed to be changed back when switching to emulation or other network communicators.

axis3x needs UDP on hardware to run without patching the ACCL driver because of issues with the axis3x design

---

test/model/zmq/zmq_client.cpp

Fix a bug in the subscription of the ZMQ client. Allow stream_put with same source and destination rank.

Small fix in ZMQ client

---

driver/xrt/Doxyfile

Fix readthedocs config of secondary classes ([example](https://accl.readthedocs.io/en/latest/cpp_bindings/cpp_reference/buffer.html)).

Hotfix doxygen configuration

---

driver/xrt/include/accl.hpp
driver/xrt/src/accl.cpp
test/host/hls/test.cpp
test/host/xrt/test.cpp

Allow to use the copy operation to copy data from stream to buffer and from buffer to stream.
Adds a test to the hls test suite to show this behavior.

Copy from and to stream

---

driver/xrt/include/accl/fpgabuffer.hpp

We do not explicitly initialize is_aligned in the FpgaBuffer class. Because of that, it may be set to false although we construct  it from a bo. memcpy will fail in this case, because the aligned_buffer is not initialized.

Explicitly init is_aligned as true

---

driver/xrt/src/accl.cpp
test/host/xrt/test.cpp

Commented the scatter compressed test out like the reduce scatter compressed test because of #130.

Actually set compression dtype in ACCL scatter call

---

driver/utils/accl_network_utils/CMakeLists.txt
driver/utils/accl_network_utils/include/accl_network_utils.hpp
driver/utils/accl_network_utils/src/accl_network_utils.cpp
test/host/hls/CMakeLists.txt
test/host/hls/test.cpp
test/host/xrt/CMakeLists.txt
test/host/xrt/test.cpp

Create a new small utility library that can initialize ACCL and the network kernels if the user adheres to the naming in the standard ACCL configs. This approach allows users to easily start using ACCL without having to write/copy a lot of setup code from the XRT test, while still allowing more advanced users to keep using ACCL in the current way.
Using the network utils library, a user now only has to call `generate_ranks` and `initialize_accl` to get an ACCL instance started.
Other advantages from using this library:
- Less duplicate code in XRT host and HLS tests (and upcoming benchmark code).
- If changes are required to the setup code, users will now automatically pull those changes in as well.
PR has been tested against hardware (UDP, TCP, axis3x) and emulator.

Add ACCL network utils

---

kernels/cclo/hls/Makefile
kernels/cclo/hls/dma_mover/dma_mover.cpp
kernels/cclo/hls/rxbuf_offload/rxbuf_enqueue.cpp
kernels/cclo/tcl/control_bd.tcl
test/host/xrt/test.cpp

Fixes #71 
Changes:
- applied reset pragmas for static variables in dma_mover
- made tags not static in rxbuf_enqueue
- reset the AXI interconnect between the offload HLS cores and the exchange memory

Fix soft reset

---

driver/utils/accl_network_utils/include/accl_network_utils.hpp
driver/utils/accl_network_utils/src/accl_network_utils.cpp
test/host/benchmark/benchmark.cpp
test/host/xrt/test.cpp

Set the session id for roce such that the constructed ip address from the subnet corresponds to the requested ip address of the rank.

Fix roce session id setup

---

test/model/simulator/run.py

On some systems, LD_LIBRARY_PATH may contain other libraries required by the simulator.

Append Vivado library path instead of replacing it in simulator

---

kernels/.gitignore

When building the simulator, per [INSTALL.md](https://github.com/Xilinx/ACCL/blob/main/INSTALL.md), ~2K files are generated by Vitis/Vivado and picked up by git, which can make version control and keeping track of changes very inconvenient.

Add gitignore for simulator

---

test/log/log.hpp
test/model/emulator/cclo_emu.cpp
test/model/simulator/cclo_sim.cpp

Extend the emulator and simulator logger to contain the local rank in the output. This should simplify debugging with the emulator and simulator when using a higher number of ranks.

Add local rank to logging output

---

test/hardware/Makefile

Target should build the whole TCP network stack in my opinion.

Add CMAC to tcp_stack target

---

driver/xrt/include/accl/fpgadevice.hpp

unordered_map is used in fpgadevice.hpp but not included.

Fix missing include

---

driver/utils/accl_network_utils/CMakeLists.txt

In my opinion, it makes sense to create a static library for the ACCL network utils. This will not change the build behavior of existing codes using CMake. But it is way easier to use the utils with other build tools like GNU Make.

Make ACCL network utils a static library

---

kernels/plugins/vadd_put/vadd_put.cpp

In the HLS example, word slicing is done like LSB...MSB, when, the correct way would be MSB...LSB. This will not cause any compile-time issues, but, can sometimes cause incorrect behaviour (e.g. summing words). An example of this is shown in this [branch](https://github.com/bo3z/ACCL/tree/broken-word-slicing) with REDUCE-SUM.
Proposing this PR for any users using the HLS test example as a baseline for their applications, as it is quite a niche bug once in the code.

Fix word slicing in HLS test

---

driver/xrt/src/accl.cpp

The count_bytes variables aren't used by the ACCL operations, but they can cause a null-pointer de-reference if the buffer doesn't exist (i.e. sendbuf in scatter on non-root ranks).

Remove unused code causing illegal memory accesses

---

kernels/cclo/hls/dma_mover/dma_mover.cpp
kernels/cclo/hls/eth_intf/rdma_depacketizer.cpp
kernels/cclo/hls/eth_intf/tcp_depacketizer.cpp
kernels/cclo/hls/eth_intf/tcp_rxHandler.cpp
kernels/cclo/hls/eth_intf/tcp_txHandler.cpp
kernels/cclo/hls/eth_intf/udp_depacketizer.cpp
test/log/log.hpp
test/model/emulator/cclo_emu.cpp

Debugging with many ranks is difficult because of the poor readability of the emulator logs. This PR improves logging by implementing the following things:
- use the logger instance of the emulator within the CCLO components
- add a mutex to the logger to prevent interleaving of messages

Improve emulator logging

---

test/host/xrt/src/test.cpp

For large world sizes, some of the unit tests fail because of wrong floating point comparison. This fix replaces all floating-point comparisons with the better-suited `EXPECT_FLOAT_EQ`.

Fix failing unit tests

---

test/model/zmq/zmq_server.cpp
test/model/zmq/zmq_server.h

The ZMQ subscription for emulator/simulator does not correctly work for more than 9 ranks, which causes the issue described in #172.
ZMQ seems to compare the subscription string with the first characters of a message. If the subscription is for rank 1, it also matches messages for rank 10,11,... 
Not sure if this is a zmqpp bug or installation specific since I did not notice this issue before. This PR fixes this issue by introducing zero-padding for the destination rank in the ZMQ messages as well as the subscription string.

Fix ZMQ subscription bug for ranks > 9

---

kernels/plugins/external_dma/gen_files.py
test/refdesigns/gen_config.py

This PR attempts to fix two issues, observed when synshteising ACCL with TCP/IP and (vadd, but possibly other) kernels.
1. The gen_files.py for external DMA by default includes TDEST signals. However, these are not always present (i.e. not present when there is one port as verified by the script bd.tcl).
2. The kernels lack stream connections to the CCLO. This is solved in a similar way to the DLRM example for OSDI, where the second hostctrl (per CCLO) is removed and those connections are used for the kernels. I am not sure if this causes any change for other applications.
This passes synthesis. I am currently testing PnR and will test on actual hardware in the following days, but the changes here should have no impact on fucntionality.

Fix extdma and kernel connections issues.

---

INSTALL.md
driver/xrt/CMakeLists.txt
test/model/bfm/CMakeLists.txt
test/model/bfm/cclo_bfm.h
test/model/emulator/CMakeLists.txt
test/model/zmq/zmq_client.cpp
test/model/zmq/zmq_common.cpp
test/model/zmq/zmq_common.h
test/model/zmq/zmq_server.cpp

Migrating to cppzmq to avoid dependency on zmqpp. Fixes #146

146 migrate to other zmq library for c++
